
-- INSERT DATA IN DEPARTMENT TABLE

insert into DEPARTMENT (DEPTNO, DNAME, LOC)
VALUES (10, 'ACCOUNTING','BANGALORE');

insert into DEPARTMENT (DEPTNO, DNAME, LOC)
VALUES (20, 'PRODUCT','CHENNAI');


insert into DEPARTMENT (DEPTNO, DNAME, LOC)
VALUES (30, 'SERVICES','DELHI');


insert into DEPARTMENT (DEPTNO, DNAME, LOC)
VALUES (40, 'SALES','MUMBAI');

insert into DEPARTMENT (DEPTNO, DNAME, LOC)
VALUES (50, 'SUPPORT','NOIDA');

insert into DEPARTMENT (DEPTNO, DNAME, LOC)
VALUES (60, 'OPS','PUNE');
